baseURL: "http://example.org"
languageCode: en-us
title: Impact Theme

theme: impact
themesDir: ../

####
## Hugo Options
####

# Disable unwanted features
disableKinds:
  - RSS
  - taxonomy
  - term

# to remove hugo meta tag
disableHugoGeneratorInject: "true"

# minify the output
minify:
  minifyOutput: "true"
  tdewolff:
    html:
      keepComments: "true"
      keepQuotes: "true"

# to use raw html in markdown files
markup:
  goldmark:
    renderer:
      unsafe: "true"

####
## Theme Options
####

googleAnalytics: "G-WKMFCHMWGS"
enableRobotsTXT: "true"

params:
  icon: assets/icon.png

  # [Optional] Pages in the footer
  privacyPage: /privacy/
  termsPage: /terms/

  # [Optional] Custom last modified title
  lastModTitle: Last modified on

  # [Optional] Global SEO
  # title: "Impact"
  # description: "Impact"
  # keywords: "Impact"
  author: Acknology Co.

  # [Optional] enable AnimateOnScroll [true|false]
  enableAOS: true
  
  # [Optional] Custom footer text
  footer:
    title: Impact Theme
    subtitle: A powerful theme for impactful websites


  # [Optional] Custom copyright text
  copyright:
    text: Acknology Co.
    url: "https://acknology.co/?utm_source=impact-theme&utm_medium=link"
    target: _blank


  ## Social Media Links    
  social:
    - name: github
      icon: fa-github
      url: "https://github.com/AcknologyHQ"
    - name: twitter
      icon: fa-twitter
      url: "https://twitter.com/AcknologyHQ"
    - name: instagram
      icon: fa-instagram
      url: "https://instagram.com/acknologyHQ"
    - name: facebook
      icon: fa-facebook-square
      url: "https://facebook.com/Acknology"
    - name: linkedin
      icon: fa-linkedin
      url: "https://linkedin.com/company/Acknology"
    - name: youtube
      icon: fa-youtube
      url: "https://youtube.com/channel/UC-lahMSaoiKxsF5kLXnpTbQ"
